In [6]:
#Create a 1D array containing numbers from 0 to 19.
#Extract only the even numbers without using a loop.
import numpy as np
arr=np.arange(0,20,2)
evens=arr[arr%2==0]
print(evens)


[ 0  2  4  6  8 10 12 14 16 18]


In [8]:
#Create a 3×3 array where the diagonal elements are 1 
#and all other elements are 0 (identity matrix).
import numpy as np
identity_matrix=np.eye(3,dtype='i')
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [20]:
#Create a 5×5 array with numbers from 1 to 25.
#(a) Extract only the corner elements.
#(b) Extract the last element of each row.
#(c) Extract the middle 3×3 block.
import numpy as np
arr=np.arange(1,26).reshape(5,5)
print(arr)
corners=np.array([arr[0,0],arr[0,-1],arr[-1,0],arr[-1,-1]])
print("Corners ",corners)
last_element=arr[:,-1]
print("Last Element ",last_element)
middle_block=arr[1:4,1:4]
print("Middle_Block",middle_block)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Corners  [ 1  5 21 25]
Last Element  [ 5 10 15 20 25]
Middle_Block [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [23]:
#Create an array a = np.arange(10).
#Take a view of it and set elements from index 3 to 7 to -1. 
#What happens to the original array?
#Do the same using a copy and compare the results.
import numpy as np
arr=np.arange(10)
a=arr.view()
a[3:7]=-1
print(arr)
b=arr.copy()
b[3:7]=-1
print(arr)

[ 0  1  2 -1 -1 -1 -1  7  8  9]
[ 0  1  2 -1 -1 -1 -1  7  8  9]


In [25]:
#Create a 1D array with 36 elements. Reshape it into:
#(a) 6×6
#(b) 3×12
#(c) 2×3×6
#Check the relationship between reshape and ravel.
import numpy as np
arr=np.arange(1,37)
a=arr.reshape(6,6)
b=arr.reshape(3,12)
c=arr.reshape(2,3,6)
print(a)
print(b)
print(c)
print("Ravel :",a.ravel())

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]]
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]]

 [[19 20 21 22 23 24]
  [25 26 27 28 29 30]
  [31 32 33 34 35 36]]]
Ravel [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [30]:
#Create two arrays: a = [1,2,3,4,5], b = [5,4,3,2,1].
#(a) Perform elementwise sum, difference, and multiplication.
#(b) Compute the dot product and outer product.
#(c) If you want to add a 1D array row-wise to a 2D array, 
#how can you use broadcasting?
import numpy as np
a=np.arange(1,6)
b=np.arange(5,0,-1)
sums=np.sum(a)
diff=np.subtract(a,b)
multi=np.multiply(a,b)
print("Sums is :",sums)
print("Difference is :",diff)
print("Product is :",multi)


Sums is : 15
Difference is : [-4 -2  0  2  4]
Product is : [5 8 9 8 5]


In [33]:
#Create a 4×4 array with random numbers.Reshape it into both 2×8 and 8×2.
ran_arr=np.random.randint(1,10,size=(4,4))
a=ran_arr.reshape(2,8)
b=ran_arr.reshape(8,2)
print("2X8",a)
print("8X2",b)

2X8 [[8 1 3 4 8 1 6 8]
 [9 5 8 5 9 5 1 3]]
8X2 [[8 1]
 [3 4]
 [8 1]
 [6 8]
 [9 5]
 [8 5]
 [9 5]
 [1 3]]
