In [5]:
#You are given a 1D array of shape (5,) and a 2D array of shape (3,5). Add the 1D array to each row of the 2D array
#using broadcasting
import numpy as np
d1=[1,2,3,4,5]
d2=np.arange(15).reshape(3,5)
addition=np.add(d1,d2)
print(addition)
print(np.shape(d1))

[[ 1  3  5  7  9]
 [ 6  8 10 12 14]
 [11 13 15 17 19]]
(5,)


In [7]:
#Multiply each column of a (3,4) array by a different scalar stored in a (4,) array.
import numpy as np
d1=[1,2,3,4]
d2=np.arange(12).reshape(3,4)
multiplication=d1*d2
print(multiplication)

[[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]]


In [11]:
#Without using np.outer, compute the outer product of two vectors (3,) and (4,).
import numpy as np
a=np.array([1,2,3]).reshape(3,1)
b=np.array([4,5,6,7])
o=a*b
print(o)

[[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]]


In [14]:
#Given a (5,5) matrix, set all elements above the main diagonal to 0.
import numpy as np
a=np.arange(25).reshape(5,5)
result=np.tril(a)
print(result)

[[ 0  0  0  0  0]
 [ 5  6  0  0  0]
 [10 11 12  0  0]
 [15 16 17 18  0]
 [20 21 22 23 24]]


In [20]:
#Construct the following block matrix using NumPy concatenation:
import numpy as np
I=np.eye(3)
z=np.zeros((3,3))
M=np.block([[I,z],[z,I]])
print(M)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [21]:
import numpy as np

A = np.array([[4, -2],
              [1,  1]])

w, v = np.linalg.eig(A)
print("Eigenvalues:", w)
print("Eigenvectors:\n", v)


Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [28]:
#Normalize each row of a 2D array so that the row sum = 1.
import numpy as np 
arr=np.arange(1,10).reshape(3,3)
row_sum=arr.sum(axis=1,keepdims=True)
result=arr/row_sum
print(np.round(result,4))

[[0.1667 0.3333 0.5   ]
 [0.2667 0.3333 0.4   ]
 [0.2917 0.3333 0.375 ]]


In [37]:
#Generate a random symmetric (4,4) matrix and confirm its eigenvalues are real.
import numpy as np
A=np.random.randn(4,4)
sym_A=(A+(A.T))/2
print(A)
print(sym_A)
values=np.linalg.eigvalsh(sym_A)
print("Is eigen values of symmetric are real ?" ,np.all(np.isreal(values)))

[[ 0.74391319  1.23340571  0.37527115 -0.95330411]
 [ 0.41155611  1.31130064 -0.61890423  0.86404404]
 [-0.09571543  1.74409038  0.6815603   0.02742811]
 [-0.02732405  1.72445464  1.06133223  0.55122544]]
[[ 0.74391319  0.82248091  0.13977786 -0.49031408]
 [ 0.82248091  1.31130064  0.56259307  1.29424934]
 [ 0.13977786  0.56259307  0.6815603   0.54438017]
 [-0.49031408  1.29424934  0.54438017  0.55122544]]
Is eigen values of symmetric are real ? True


In [52]:
#Solve Ax = b in the least squares sense, where A is (5,3) and b is (5,).
import numpy as np 
A=np.arange(1,16).reshape(5,3)
b=np.arange(1,6)
x,residuals,rank,s=np.linalg.lstsq(A,b)
print(x)
print(residuals)
print(rank)
print(s)

[-0.05555556  0.11111111  0.27777778]
[]
2
[3.51826483e+01 1.47690770e+00 1.65564886e-15]


In [66]:
#euclidean 

import numpy as np 
A=np.arange(1,7).reshape(3,2)
print(A)
diff=A[:,None,:]-A[None,:,:]
print(diff)
sq=np.sum(diff**2,axis=-1)
sqrt=sq**0.5
print(sqrt)

[[1 2]
 [3 4]
 [5 6]]
[[[ 0  0]
  [-2 -2]
  [-4 -4]]

 [[ 2  2]
  [ 0  0]
  [-2 -2]]

 [[ 4  4]
  [ 2  2]
  [ 0  0]]]
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [70]:
#manhattan
import numpy as np
A=np.arange(1,13).reshape(3,4)
diff=A[:,None,:]-A[None,:,:]
sums=np.sum(np.abs(diff),axis=-1)
print(sums)

[[ 0 16 32]
 [16  0 16]
 [32 16  0]]


In [75]:
#minkowiski
import numpy as np 
r=int(input("Enter the power"))
A=np.arange(1,16).reshape(3,5)
diff=A[:,None,:]-A[None,:,:]
power=np.sum(np.abs(diff)**r,axis=-1)
root=power**(1/r)
print(root)

Enter the power 4


[[ 0.          7.47674391 14.95348781]
 [ 7.47674391  0.          7.47674391]
 [14.95348781  7.47674391  0.        ]]
