In [4]:
#Create a 1D array of numbers from 1 to 10 using NumPy and print it
import numpy as np
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
#Create a 2D array (3 rows × 4 columns) filled with zeros and display its shape and dimension.
import numpy as np
arr=np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0]])
print("3 x 4 table of zero look like :",arr)
print("dimension of 3 x 4 table is :",arr.ndim)
print("the shape is :",arr.shape)

3 x 4 table of zero look like : [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
dimension of 3 x 4 table is : 2
the shape is : (3, 4)


In [13]:
#Create an array of even numbers from 2 to 20 and print the data type of the array.
import numpy as np
arr=np.arange(2,21,2)
print(arr)


[ 2  4  6  8 10 12 14 16 18 20]


In [17]:
#Create a 3D array of shape (2, 3, 4) with random integers between 1 and 50. Print:
#Shape,Number of dimensions,Size (total elements),
import numpy as np
arr=np.array(
    [
        [[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]
    ]  
)
print("the array is :",arr)
print("the shape of array:",arr.shape)
print("the dimension of arrays",arr.ndim)
print("the size of array ",arr.size)


the array is : [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
the shape of array: (2, 3, 4)
the dimension of arrays 3
the size of array  24


In [20]:
#Convert a 1D array [1,2,3,4,5,6,7,8,9] into a 3×3 2D array and print it 
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
arr_matrix=arr.reshape(3,3)
print(arr_matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
#Flatten a 2D array of shape (4, 3) into a 1D array and print the result.
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
flatten=arr.reshape(-1)
print(flatten)

[1 2 3 4 5 6]


In [30]:
#Given an array
#arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
#Print:The element at row 1, column 2,The entire second row,The entire second column
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0][1])
print(arr[1])
print(arr[:,1])

20
[40 50 60]
[20 50 80]


In [33]:
#Create a 1D array of numbers from 10 to 50 (step = 5). Print only the elements at even indices.
import numpy as np
arr=np.arange(10,51,5)
print(arr)
print(arr[::2])

[10 15 20 25 30 35 40 45 50]
[10 20 30 40 50]


In [43]:
#From the array
arr = np.arange(1, 26).reshape(5, 5)
#Print:#First 2 rows,#Last 2 columns,#Middle element
print("First 2 rows :",arr[0:2])
print("Last 2 colums :",arr[:,3:5])
print("Middle Element: ",arr[2,2])

First 2 rows : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last 2 colums : [[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]
Middle Element:  13


In [52]:
#Given
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#Print:The element 6 using indexing,The sub-array [[7,8,9],[10,11,12]],All elements from the first row of the first block
print(arr[0,1,2])
print(arr[1])
print(arr[0,0])

6
[[ 7  8  9]
 [10 11 12]]
[1 2 3]
