In [5]:
#Given a 2D NumPy array, write code to calculate the sum of 
#only the border elements (first row, last row, first column, last column).
import numpy as np 
d2=np.arange(16).reshape(4,4)
top=d2[0,:]
bottom=d2[-1,:]
left=d2[1:-1,0]
right=d2[1:-1,-1]
sum=top.sum()+bottom.sum()+right.sum()+left.sum()
print(sum)

90


In [15]:
#For a given NumPy array, replace all values that are greater than
#mean + 2×std or less than mean - 2×std with the array mean.
import numpy as np
arr=np.arange(12).reshape(4,3)
mean=arr.mean()
std=arr.std()
sums=mean + 2 * std
subs=mean - 2 * std
mask= (arr>sums) | (arr<subs)
arr[mask]=mean
print(arr)



5.5
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[1. 1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 9.]]


In [35]:
import numpy as np
arr=[[3,5,4],[6,5,2],[9,1,5]]
print(arr)
rank=np.argsort(arr)+1
print(rank)

[[3, 5, 4], [6, 5, 2], [9, 1, 5]]
[[1 3 2]
 [3 2 1]
 [2 3 1]]


In [60]:
#Given a 2D array of points X (shape (n, d)),
#compute the distance matrix where D[i, j] is the Euclidean distance between point i and point j.
X=np.arange(1,7).reshape(3,2)
diff=X[:,None,:]-X[None,:,:]
Sq=np.sum(np.abs(diff)**2,axis=-1)
sqrt=Sq**0.5
print(sqrt)

[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]
