In [7]:
#using trignometric function 
import numpy as np
angles=np.array([0,30,45,60,90,120,180])
radians=np.deg2rad(angles)
print("Sine of Angles",np.sin(radians))
print("Inverse sine of sine values",np.rad2deg(np.arcsin(np.sin(radians))))
      

Sine of Angles [0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 8.66025404e-01 1.22464680e-16]
inverse sine of sine values [0.0000000e+00 3.0000000e+01 4.5000000e+01 6.0000000e+01 9.0000000e+01
 6.0000000e+01 7.0167093e-15]


In [8]:
# Python code to demonstrate matrix operations 
# multiply() and dot() 

# importing numpy for matrix operations 
import numpy 

# initializing matrices 
x = numpy.array([[1, 2], [4, 5]]) 
y = numpy.array([[7, 8], [9, 10]]) 

# using multiply() to multiply matrices element wise 
print ("The element wise multiplication of matrix is : ") 
print (numpy.multiply(x,y)) 

# using dot() to multiply matrices 
print ("The product of matrices is : ") 
print (numpy.dot(x,y))

The element wise multiplication of matrix is : 
[[ 7 16]
 [36 50]]
The product of matrices is : 
[[25 28]
 [73 82]]


In [13]:
#Random Seed Reproducibility
#Create two 5×5 arrays with random integers between 10 and 99 such that:
#The first and last rows of both arrays are identical
#The inner 3×5 elements differimport numpy as np
arr=np.random.randint(10,99,size=(5,5))
values=np.random.randint(10,99)
arr[0,:]=values
arr[-1,:]=values
print(arr)

[[56 56 56 56 56]
 [88 31 34 78 67]
 [69 61 96 59 36]
 [90 25 38 26 74]
 [56 56 56 56 56]]


In [ ]:
#Without using loops, create a 7×7 array where:
#The main diagonal is all 1’s
#The upper diagonal is filled with 2’s
#The lower diagonal is filled with -2’s
arr=np.eye(7)


In [25]:
import numpy as np
a=np.array([3,2,6])
b=np.array([4,8,9])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[7,8,9],[10,11,12]])
e=np.array([[7,10],[8,11],[9,12]])
mult=np.multiply(a,b)
mult2=np.multiply(c,d)
dot1=np.dot(a,b)
dot2=np.dot(c,e)
inner1=np.inner(c,d)
outer1=np.outer(a,b)
cross1=np.cross(a,b)
cross2=np.cross(c,d)
print(mult)
print(mult2)
print(dot1)
print(dot2)
print(outer1)
print(cross1)
print(cross2)

[12 16 54]
[[ 7 16 27]
 [40 55 72]]
82
[[ 50  68]
 [122 167]]
[[12 24 27]
 [ 8 16 18]
 [24 48 54]]
[-30  -3  16]
[[-6 12 -6]
 [-6 12 -6]]
